{{- if .Values.ingress.cert -}}
{{- $domain := .Values.ingress.host.back -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-crt-back
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-crt-back
  dnsNames:
    - {{ $domain }}
  tls:
    - {{ $domain }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ $domain }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{- end }}