{{- if .Values.ingress.enabled -}}
{{- $fullName := include "artipub-charts.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $svcbackPort := .Values.service.backport -}}
{{- $svcPort := .Values.service.port -}}
{{- $domain := .Values.ingress.host.name -}}
{{- $back := .Values.ingress.host.back -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "artipub-charts.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.cert }}
  tls:
    - hosts:
      - {{ $domain }}
      secretName: {{ .Release.Name }}-crt
    - hosts:
      - {{ $back }}
      secretName: {{ .Release.Name }}-crt-back
{{- end }}
  rules:
    - host: {{ $domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
    - host: {{ $back }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcbackPort }}
{{- end }}
